-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.alembic_version
(
    version_num character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

CREATE TABLE IF NOT EXISTS public.chat_histories
(
    id serial NOT NULL,
    interview_id integer NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    user_id bigint NOT NULL,
    CONSTRAINT chat_histories_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    id bigserial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    location character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT companies_pkey PRIMARY KEY (id),
    CONSTRAINT companies_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.interview_questions
(
    id serial NOT NULL,
    interview_id integer NOT NULL,
    question character varying COLLATE pg_catalog."default" NOT NULL,
    expected_answer character varying[] COLLATE pg_catalog."default",
    user_answer character varying COLLATE pg_catalog."default",
    score double precision,
    reason character varying COLLATE pg_catalog."default",
    CONSTRAINT interview_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interview_summaries
(
    id serial NOT NULL,
    interview_id integer NOT NULL,
    total_score double precision,
    experience_score double precision,
    communication_score double precision,
    technical_score double precision,
    recommendation character varying COLLATE pg_catalog."default",
    confidence double precision,
    strengths json,
    weaknesses json,
    red_flags text[] COLLATE pg_catalog."default",
    evidence json,
    suggestion_summary text COLLATE pg_catalog."default",
    next_step text COLLATE pg_catalog."default",
    CONSTRAINT interview_summaries_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interviews
(
    id serial NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'waiting'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    user_id bigint NOT NULL,
    job_id bigint NOT NULL,
    context character varying COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    candidate_profile_summary character varying COLLATE pg_catalog."default",
    job_profile_summary character varying COLLATE pg_catalog."default",
    candidate_strengths character varying COLLATE pg_catalog."default",
    candidate_gaps character varying COLLATE pg_catalog."default",
    hr_interest character varying COLLATE pg_catalog."default",
    difficulty double precision DEFAULT '0.5'::double precision,
    CONSTRAINT interviews_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.jobs
(
    id bigserial NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    responsibilities character varying[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::character varying[],
    qualifications character varying[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::character varying[],
    skills character varying[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::character varying[],
    headcount integer NOT NULL,
    "minAge" integer NOT NULL,
    "maxAge" integer NOT NULL,
    "minSalary" integer NOT NULL,
    "maxSalary" integer NOT NULL,
    "postedAt" timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    job_fields character varying[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::character varying[],
    user_id bigint NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT jobs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resume_education
(
    id bigserial NOT NULL,
    resume_id bigint NOT NULL,
    institution character varying(255) COLLATE pg_catalog."default" NOT NULL,
    degree character varying(255) COLLATE pg_catalog."default",
    faculty character varying(255) COLLATE pg_catalog."default",
    major character varying(255) COLLATE pg_catalog."default",
    gpax double precision,
    start_year integer,
    start_month integer,
    end_year integer,
    end_month integer,
    CONSTRAINT resume_education_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resume_experience
(
    id bigserial NOT NULL,
    resume_id bigint NOT NULL,
    company character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default",
    start_year integer,
    start_month integer,
    end_year integer,
    end_month integer,
    description text COLLATE pg_catalog."default",
    CONSTRAINT resume_experience_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resume_projects
(
    id bigserial NOT NULL,
    resume_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT resume_projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resume_skills
(
    id bigserial NOT NULL,
    resume_id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT resume_skills_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resumes
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    age integer,
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    pdf_path character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT resumes_pkey PRIMARY KEY (id),
    CONSTRAINT resumes_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id bigserial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    role character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'candidate'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS public.chat_histories
    ADD CONSTRAINT chat_histories_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.chat_histories
    ADD CONSTRAINT chat_histories_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.companies
    ADD CONSTRAINT companies_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS companies_user_id_key
    ON public.companies(user_id);


ALTER TABLE IF EXISTS public.interview_questions
    ADD CONSTRAINT interview_questions_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interview_summaries
    ADD CONSTRAINT interview_summaries_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interviews
    ADD CONSTRAINT interviews_job_id_fkey FOREIGN KEY (job_id)
    REFERENCES public.jobs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interviews
    ADD CONSTRAINT interviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.jobs
    ADD CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resume_education
    ADD CONSTRAINT resume_education_resume_id_fkey FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resume_experience
    ADD CONSTRAINT resume_experience_resume_id_fkey FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resume_projects
    ADD CONSTRAINT resume_projects_resume_id_fkey FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resume_skills
    ADD CONSTRAINT resume_skills_resume_id_fkey FOREIGN KEY (resume_id)
    REFERENCES public.resumes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.resumes
    ADD CONSTRAINT resumes_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS resumes_user_id_key
    ON public.resumes(user_id);

END;