"""create_jobs_table

Revision ID: 091812eda8ed
Revises: d7a7272d7b4b
Create Date: 2026-02-25 01:00:06.687137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '091812eda8ed'
down_revision: Union[str, Sequence[str], None] = 'd7a7272d7b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('qualifications', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('minAge', sa.Integer(), nullable=False),
    sa.Column('maxAge', sa.Integer(), nullable=False),
    sa.Column('minSalary', sa.Integer(), nullable=False),
    sa.Column('maxSalary', sa.Integer(), nullable=False),
    sa.Column('postedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
