"""add_company_profile_and_update_jobs

Revision ID: 0ae608c8a836
Revises: 41e5bc590167
Create Date: 2026-03-03 13:40:29.759550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae608c8a836'
down_revision: Union[str, Sequence[str], None] = '41e5bc590167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'company')
    op.drop_column('jobs', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
