"""add user into chat_hotories

Revision ID: 729bbf96eba0
Revises: 5a71e20f539c
Create Date: 2026-03-08 21:59:48.723467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729bbf96eba0'
down_revision: Union[str, Sequence[str], None] = '5a71e20f539c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'chat_histories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_column('chat_histories', 'user_id')
    # ### end Alembic commands ###
