"""chat

Revision ID: d746c0795f8e
Revises: 4e7527bea7f4
Create Date: 2026-03-08 17:14:40.412152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd746c0795f8e'
down_revision: Union[str, Sequence[str], None] = '4e7527bea7f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_histories_id'), 'chat_histories', ['id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('expected_answer', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.add_column('interviews', sa.Column('candidate_profile_summary', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('job_profile_summary', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('candidate_strengths', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('candidate_gaps', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('hr_interest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'hr_interest')
    op.drop_column('interviews', 'candidate_gaps')
    op.drop_column('interviews', 'candidate_strengths')
    op.drop_column('interviews', 'job_profile_summary')
    op.drop_column('interviews', 'candidate_profile_summary')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_chat_histories_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    # ### end Alembic commands ###
