"""upload pdf_path into resume

Revision ID: f42723dd8f4b
Revises: 9e992decff38
Create Date: 2026-03-07 19:57:22.675744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42723dd8f4b'
down_revision: Union[str, Sequence[str], None] = '9e992decff38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('pdf_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'pdf_path')
    # ### end Alembic commands ###
