"""update resume types

Revision ID: 41e5bc590167
Revises: c311433c788a
Create Date: 2026-03-03 12:40:11.445343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e5bc590167'
down_revision: Union[str, Sequence[str], None] = 'c311433c788a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume_education', 'gpax',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using="gpax::double precision")
    op.alter_column('resumes', 'age',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="age::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('resume_education', 'gpax',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
