"""chat

Revision ID: 4e7527bea7f4
Revises: f42723dd8f4b
Create Date: 2026-03-08 17:08:49.980109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7527bea7f4'
down_revision: Union[str, Sequence[str], None] = 'f42723dd8f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_column('interviews', 'candidate_strengths')
    op.drop_column('interviews', 'candidate_profile_summary')
    op.drop_column('interviews', 'job_profile_summary')
    op.drop_column('interviews', 'candidate_gaps')
    op.drop_column('interviews', 'hr_interest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('hr_interest', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('candidate_gaps', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('job_profile_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('candidate_profile_summary', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('candidate_strengths', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('interview_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expected_answer', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('interview_questions_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_questions_pkey'))
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_table('chat_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('chat_histories_interview_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_histories_pkey'))
    )
    op.create_index(op.f('ix_chat_histories_id'), 'chat_histories', ['id'], unique=False)
    # ### end Alembic commands ###
