"""interview state

Revision ID: 5a71e20f539c
Revises: d746c0795f8e
Create Date: 2026-03-08 19:15:18.431818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a71e20f539c'
down_revision: Union[str, Sequence[str], None] = 'd746c0795f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('difficulty', sa.Float(), server_default='0.5', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'difficulty')
    # ### end Alembic commands ###
